Blur background
capacitor-community/privacy-screen pull request #34
Opened 2021-07-13 18:33 UTC by oneclickwebstudio

Hi. I've added Blur effect instead of grey color. I think it looks nice

2021-07-14 19:19 UTC, robingenz commented
Thank you for your PR.
I will try to test it this weekend.

2021-07-16 18:07 UTC, robingenz requested changes

2021-07-16 18:07 UTC, robingenz commented on ios/Plugin/PrivacyScreenPlugin.swift
> +            self.privacyViewController!.view.addSubview(blurEffectView) //if you have more UIViews, use an insertSubview API to place it where needed
Please remove this comment.

2021-07-16 18:16 UTC, robingenz commented
LGTM. I'm just wondering if this should be the default or if you should be able to configure it.
I will think about it.
Thanks a lot already!

2021-09-17 21:13 UTC, inexuscore commented
I just wanted to request this feature. It would be amazing if we could have a blur effect instead of a black screen. Could this be supported on both Android and iOS? Any ideas when this would be available? Thank you very much.

2021-09-18 19:23 UTC, robingenz commented
I would like to provide a configuration option to select the background color/effect. 
Unfortunately, I have not much time at the moment. Suggestions are welcome.

2021-09-20 13:07 UTC, robingenz commented
Please merge the `main` branch and resolve the merge conflicts so I can see the changes.

2023-03-20 12:26 UTC, closed without merging