fix: disable/enable methods iOS
capacitor-community/privacy-screen pull request #87
Opened 2024-03-05 21:55 UTC by jonas-elias

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [x] The changes have been tested successfully.

Resolves:
- https://github.com/capacitor-community/privacy-screen/issues/84
- https://github.com/capacitor-community/privacy-screen/issues/82

2024-03-05 22:37 UTC, rafael-cdo commented
Up!

2024-03-06 09:24 UTC, robingenz commented
Thank you for the PR. I'll review it after work.

2024-03-07 13:44 UTC, robingenz requested changes
Thank you for your PR! Please run `npm run fmt` to format your changes.

2024-03-08 07:42 UTC, robingenz approved these changes

2024-03-08 07:43 UTC, merged